export { getCommentsFromFile } from './getCommentsFromFile/index.js'
export { getTag } from './getTag/index.js'
export { parse } from './parse/index.js'
export { parseTags } from './parseTags/index.js'
export { removeTags } from './removeTags/index.js'
export { toCommentString } from './toCommentString/index.js'
